### ISSUE TITLE
plugin Notification 

### ISSUE THREAD

**Issue by lorsistem** [sjarvela/mollify#11]
hello happy to greet you , this time you contact because I wonder if you can give me some manual or documentation that tells me how the plugin works notification , note that I have already enabled been reading reviews of other users too well seems to have enabled the plugin

![image](https://cloud.githubusercontent.com/assets/11165554/6628082/d108cbc2-c8d4-11e4-8316-ee52c33ee680.png)

I just do not know where or how come the notifications, I inform you that here we have a SMTP server exchange and attempt to use it as a mail server settings this is to add in the configuration.php

![image](https://cloud.githubusercontent.com/assets/11165554/6628114/179cee9c-c8d5-11e4-8a24-ed8a4d7b7d27.png)

and that host information also add it in the php.ini SMTP

really appreciate your help is that derrepente 'm abusing you but would be eternally grateful.

thx
Greetings ..

**Comment by sjarvela** [comment]
I added wiki page for this: https://github.com/sjarvela/kloudspeaker/wiki/Mail

Can't say why mail is not sent, you should check your logs and server configuration that you are using correct values. Option secure should be "tls" or "ssl", not TRUE, and you should leave it out if you are not using any of these.

**Comment by sjarvela** [comment]
Closing as there is no progress. Further discussion should be continued at https://github.com/sjarvela/kloudspeaker/
