### ISSUE TITLE
Restoring a version

### ISSUE THREAD

**Issue by luke7263** [sjarvela/mollify#15]
In history plugin, when restoring a version, it would be useful in the restore confirmation message to add date and size informations:

"Are you sure you want to restore version for filename from {date of file} and  {size of file} bytes ?"

**Comment by sjarvela** [comment]
Added, will be in next Kloudspeaker release (not going to move these issues to kloudspeaker, just gonna close them here after released)

**Comment by sjarvela** [comment]
In 2.6.8
