### ISSUE TITLE
IE bad filename when i'm downloading a file

### ISSUE THREAD

**Issue by Bookash** [sjarvela/mollify#2]
Hi.
Installed your latest version.
When i try to download a file with non ascii filename (Документ Microsoft Office Word.docx) i got a file with filename (Р”РѕРєСѓРјРµРЅС‚ Microsoft Office Word.docx)

solution:
change OutputHandler.Class.php in private function sendDownloadHeaders($filename, $type, $mobile, $size)
old: header("Content-Disposition: attachment; filename=\"".$filename."\";");
new: header('Content-Disposition: attachment; filename*=UTF-8\'\''.rawurlencode($filename));

**Comment by sjarvela** [comment]
Thanks for the suggestion. Have to test if this works in other browsers as well.

**Comment by sjarvela** [comment]
Added, will be in next Kloudspeaker release

**Comment by sjarvela** [comment]
In 2.6.8
