### ISSUE TITLE
password for users

### ISSUE THREAD

**Issue by peeterss** [sjarvela/mollify#5]
version 2.6.4
creating a user errors on save, can't login afterwards.

i can be more specific..

**Comment by peeterss** [comment]
"debug" => true,
	
	"enable_change_password" => TRUE,
	"no_udev_random" => true, 

fixed it.  
make sure you set debug back to false in backend/configuration.php ..

**Comment by sjarvela** [comment]
Some changes in the settings/features logic dropped the password feature from being enabled by default, I'll change this.

**Comment by peeterss** [comment]
tnx    nice stuff.
